name: "Build and deploy"

on:
  push:
    branches:
      - 'main'
      - 'release'
      - 'chore_release-*'
      - 'build-*'
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CI: true

jobs:
  build:
    name: "app build"
    strategy:
      matrix:
        os: ["windows-2022", "ubuntu-22.04", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          fetch-depth: 0
      - uses: "pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2" # v2.0.2
        with:
          cache: true
      - uses: "extractions/setup-crate@7577c1bdf2d95e6d65d532788f35ed79d4b1dda2" # v2.0.1
        with:
          repo: casey/just
          version: 1.58.0
      - name: "Setup"
        run: just setup
      - name: "Build"
        run: just build
      - name: "Upload artifact"
        id: "artifact-upload"
        uses: "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a" # v7.0.1
        with:
          name: "logviewer-${{matrix.os}}-${{github.run_id}}"
          path: "app-shell/build/*"
      - name: "Artifact result"
        run: echo "Artifact is ${{ steps.artifact-upload.outputs.artifact-url }}"
